apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-storage-secret-provider
spec:
  provider: azure
  parameters:
    keyvaultName: <your-keyvault-name>
    objects:  |
      array:
        - |
          objectName: azure-storage-secret
          objectType: secret
    resourceGroup: <your-resource-group>
    subscriptionId: <your-subscription-id>
    tenantId: <your-tenant-id>
